# This is a basic workflow to show using this action

# name of the workflow
name: Check dbt Cloud Job Run Status

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab if needed
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  dbt_cloud_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with dbt Cloud
        uses: dbt-labs/dbt-cloud-auth@v2.0.0
        with:
          dbt_cloud_api_token: ${{ secrets.DBT_CLOUD_API_TOKEN }}
          dbt_cloud_account_id: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}

      - name: Trigger dbt Cloud Job
        uses: dbt-labs/run-dbt-cloud-job@v2.0.0
        with:
          dbt_cloud_job_id: ${{ secrets.DBT_CLOUD_JOB_ID }}  # Job ID from dbt Cloud
          wait_for_job_completion: true