name: Deploy dbt
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job's status is ${{ job.status }}."

  deploy:
      runs-on: ubuntu-latest
      #needs: test    # Ensure tests pass before deploying
      #if: github.ref == 'refs/heads/main' && job.test.outcome == 'success'  # Deploy only on successful tests in the main branch

      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - name: Install dbt
          run: pip install dbt-bigquery
        - name: Set up Google Cloud Platform credentials
          uses: google-github-actions/setup-gcloud@v1
          with:
            project_id: ${{ secrets.BIGQUERY_PROJECT_ID }}
            service_account_key: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}
        - name: dbt deploy
          run: dbt run --profiles-dir . --target prod --full-refresh

          The workflow is not valid. .github/workflows/github-actions.yml (Line: 14, Col: 11): Unrecognized named-value: 'job'. Located at position 36 within expression: github.ref == 'refs/heads/main' && job.test.outcome == 'success'
