name: Deploy dbt Project on Pull Request

on:
  pull_request:
    branches:
      - main
      - alanperez89-patch-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger dbt Cloud job
      env:
        DBT_CLOUD_API_TOKEN: ${{ secrets.DBT_CLOUD_TOKEN }}
      run: |
        curl --request POST \
          --url https://cloud.getdbt.com/api/v2/accounts/{70403103928636}/jobs/{70403103937422}/run/ \
          --header "Authorization: Token $DBT_CLOUD_TOKEN" \
          --header "Content-Type: application/json" \
          --data '{"cause": "Triggered by GitHub Actions"}' 